
stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - deploy

before_script:
  - echo " INFO Running before_script, setting up requirements"

.base_docker: &base_docker
  before_script:
    - echo " INFO Running before_script, setting up requirements on alma9"
    - dnf install -y epel-release
    - dnf install -y arm-none-eabi-binutils-cs.x86_64 arm-none-eabi-gcc-cs.x86_64 arm-none-eabi-gcc-cs-c++.x86_64 arm-none-eabi-newlib.noarch make git
    - PROJDIR=$(pwd)
    - cd && git clone https://git.code.sf.net/p/openocd/code && cd code
    - dnf -y install libusbx-devel libusb libusbx which libtool libftdi libftdi-devel
    - ./bootstrap && ./configure --enable-ti-icdi --enable-openjtag  --enable-xds110
    - make
    - make install
    - openocd --version
    - cd $PROJDIR


build-job:       # This job runs in the build stage, which runs first.
  <<: *base_docker
  image: almalinux:9
  stage: build
  tags:
    - docker
  script:
    - echo "Compiling driverlib..."
    - make -C driverlib/
    - echo "Compiling the code..."
    - make check-and-reinit-submodules
    - export FREERTOS_ROOT=$(pwd)/FreeRTOS-Kernel
    - make DEVBOARD=1 DEBUG=1 PART=TM4C1294NCPDT
    - echo "Compile complete."
  artifacts:
    paths:
      - projects/mpi_mcu/gcc/mpi_mcu.axf
      - projects/mpi_mcu/gcc/mpi_mcu.bin
    expire_in: 1 year

test-job:
  tags: 
    - umassminipc02
  script:
    - ls projects/mpi_mcu/gcc/mpi_mcu.axf
    - openocd --version
    - openocd -f /usr/local/share/openocd/scripts/board/ti_ek-tm4c1294xl.cfg -c "program projects/mpi_mcu/gcc/mpi_mcu.axf verify reset exit"
    - timeout 10 cat </dev/ttyACM0 || true
    - tester/test_mpi_mcu.py -v